---

- include_tasks: "pkg_{{ ansible_facts['distribution'] }}"

- name: force ansible to regather facts
  setup:

- name: create ssh-access group
  group:
    name: ssh-access
    system: True

- name: create ansible user
  user:
    name: ansible
    home: /home/ansible
    system: True
    groups:
      - ssh-access
    append: True

- name: add ssh authorized keys
  authorized_key:
    user: ansible
    key: "{{ item }}"
  loop: "{{ requirements_ansible_ssh_authorized_keys }}"

- include_tasks: "sudo_{{ ansible_facts['distribution'] }}"
