---

# We probably don't know yet what the server is.
# So we must use a 'group' to determine it.

- import_tasks: pkg_Debian.yml
  when: >
    'Debian' in groups
    and inventory_hostname in groups['Debian']

- import_tasks: pkg_OpenBSD.yml
  when: >
    'OpenBSD' in groups
    and inventory_hostname in groups['OpenBSD']

- name: force ansible to regather facts
  setup:

- name: create ssh-access group
  group:
    name: ssh-access
    system: True

- name: create ansible user
  user:
    name: ansible
    home: /home/ansible
    system: True
    groups:
      - ssh-access
    append: True

- name: add ssh authorized keys
  authorized_key:
    user: ansible
    key: "{{ item.key }}"
    key_options: "{{ item.key_options | default(omit) }}"
    exclusive: False
  loop: "{{ requirements_ansible_ssh_authorized_keys }}"

- import_tasks: sudo_Debian.yml
  when: >
    'Debian' in groups
    and inventory_hostname in groups['Debian']

- import_tasks: sudo_OpenBSD.yml
  when: >
    'OpenBSD' in groups
    and inventory_hostname in groups['OpenBSD']
