---

- name: install minimal ansible python libs
  raw: |
    apt-get -y -o "APT::Install-Recommends=false" -o "APT::Install-Suggests=false" install apt-transport-https python3-openssl python3-ndg-httpsclient python3-pyasn1 python3-pip python3-virtualenv
#  raw: |
#    apt-get -y -o "APT::Install-Recommends=false" -o "APT::Install-Suggests=false" install apt-transport-https python-openssl python-ndg-httpsclient python-pyasn1 python-pip python-virtualenv
  changed_when: False
