---

- name: create ansible sudoers file
  include_role:
    name: t18s.fr_sudoers
  vars:
    sudoers_name: ansible
    sudoers_state: present

    sudoers_defaults:
      - requiretty: False
        from: ansible

    sudoers_rules:
      - from: ansible
        as: ALL
        nopasswd: True
        commands: ALL
