---

- hosts: all
  name: 'Verify'
  become: True
  gather_facts: True
  vars:
    __verify_ansible_sudo_by_os_family:
      Debian: "su -s /bin/bash ansible -c 'sudo /usr/bin/whoami'"
      OpenBSD: "su -s /bin/ksh ansible -c 'doas /usr/bin/whoami'"

  tasks:
    - name: 'Check the ansible user can privesc'
      shell: "{{ __verify_ansible_sudo_by_os_family[ ansible_facts['os_family'] ] }}"
      register: __verify_cmd
      failed_when: __verify_cmd.stdout != 'root'
